### ISSUE TITLE
Functional View on top of the JUnit Jupiter Extension API

### ISSUE THREAD

**Issue by svenruppert** [junit-pioneer/junit-pioneer#139]
The Core API could be extended with an official functional view. Means, that the developer would have the choice between "oo" or "functional" approach. The functional API should be Core Java only, no ByteCode manipulation to be available from JDK8 up to JDKxx without changes.

## Example Ideas..

```java
  static Function<ExtensionContext, ExtensionContext.Store> storeGlobal() {
    return (context) -> context.getStore(NAMESPACE_GLOBAL);
  }
  static Function<ExtensionContext, ExtensionContext.Store> store() {
    return (context) -> context.getStore(namespaceFor().apply(context));
  }
  static Function<ExtensionContext, BiConsumer<String, Object>> storeObjectIn() {
    return (context) -> (key, value) -> store().apply(context).put(key, value);
  }

  static Function<ExtensionContext, Consumer<String>> removeObjectIn() {
    return (context) -> (key) -> store().apply(context).remove(key);
  }
```

## Deliverables
I would like to deliver 
- [ ] the Core Java API for the functional view on top of the JUnit Jupiter Extension API.
- [ ] the documentation about the API
- [ ] coding examples how to use it

**Comment by smoyer64** [comment]
I remember seeing https://github.com/junit-team/junit5/issues/1743 ... sorry I missed that you added the issue here.

Since the junit-pioneer library is supposed to be community extensions, my opinion is that adding a functional "aspect" should be a separate library.  If you'd like to be the maintainer under the junit-pioneer umbrella, I can create a repository for you.  I think the groupId should be something like ``org.junit-pioneer.functional`` and perhaps the artifactIds should mirror the JUnit 5 package names.

**Comment by nicolaiparlog** [comment]
@svenruppert I just took a look at the examples in junit-team/junit5#1743 and I have to admit that I don't quite see the connection to JUnit 5, either. As I see it, what you describe focuses on assertions, which are independent of the test framework. How does that relate to "the Core Java API for the functional view on top of the JUnit Jupiter Extension API"? In that light, I disagree with @smoyer64 and would not (yet) put this under the roof of Pioneer.

Maybe it's just tough to explain, though. Since you're willing to implement this feature set anyway, why not do just that and come back with a working prototype if you're still interested to make it part of Pioneer. It's not like we have huge traction that you're missing out on. :wink:

**Comment by svenruppert** [comment]
ok
