### ISSUE TITLE
Improve ReportEntry Extension

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#179]
Once #134 is fixed by #173 we could add more features to the extension. Random ideas:

* introduce variables, e.g. for test name or arguments
* introduce switch when to log, e.g. before or after or on failure
* should there be a way to specify multiple key/value pairs in a single annotation, so they can be put into a map and published as a single report entry?

**Comment by Michael1993** [comment]
Yeah, sure, I would like to try this.

I'm not really keen on the third option but the other two is sorely needed for the extension to feel more 'complete'.

**Comment by nicolaiparlog** [comment]
The prerequisite #134/#173 are done. Let me know, when you (or anybody else) starts working on this.

**Comment by Michael1993** [comment]
I have something in the works but it might take some time as I'm figuring things out. I don't want to make another half-cooked PR and dumb hours of work on you. :worried:

**Comment by nicolaiparlog** [comment]
On the next iteration you (or somebody else) has to add your contribution to the README.

**Comment by Bukama** [comment]
To give a short information what was implemented and what is open for discussion / implementation from my personal point of view:

> * introduce variables, e.g. for test name or arguments

This seems quite useful to me. For arguments I understand something like this:

```
String[] params = {"A", "B", "C"};
...
@ReportEntry(value = "Some entry {0}, {1} and {2}")
```
and for names something like `{displayName} or `{classDisplayName}`, which would result in @ReportEntry(value = "Some entry for {displayName}")`


> * introduce switch when to log, e.g. before or after or on failure

Was talked about yesterday at stream: @Michael1993 has implemented a publish condition to choose when a report entry should be published. Options are : always, on success, on failure and when test was aborted. This resolved one part of this point as the entries are published always at the end of the test execution. I personally see this feature done.


> * should there be a way to specify multiple key/value pairs in a single annotation, so they can be put into a map and published as a single report entry?

Not sure if I understand it correctly but when I don't see a use case here, because the annotation is repeatable. Only case may be grabbing the parameters of a `@ParameterizedTest` - if this is possible at all.

**Comment by nicolaiparlog** [comment]
I'm still very interested in this, @Michael1993, and since we down to a single-digit of open PRs, you might as well open a new one, if you have anything to show. :)

**Comment by Michael1993** [comment]
Not sure about test names. Should that be added too?

**Comment by Bukama** [comment]
> Not sure about test names. Should that be added too?

I don't see the need for it as `ReportEntries` are published under a unique qualified name (of the test) anyway.

**Comment by Michael1993** [comment]
I believe this issue is done for now. If anyone finds a new use-case/has an improvement idea that requires further updates, feel free to re-open this.
