### ISSUE TITLE
Create Separate Documentation (?)

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#19]
Consider whether documentation beyond a README (#18) and Javadoc (#12) is necessary.

**Comment by nicolaiparlog** [comment]
When working on this I operated on the so far undiscussed assumption that we would like to have documentation beyond Javadoc.

My reason for that is that I just liked the idea of having SEO and social media friendly documentation. Single page documentations (like JUnit 5's) and Javadoc are typically poorly indexed and do not rank very high, making the best documentation harder to find than necessary. Instead I wanted a single, blog-post like document for every aspect of the API.

A proof of concept is already online at [junit-pioneer.org](http://junit-pioneer.org/docs/disabled/). Particularly note that:

* the ToC on the left makes it easy to see available features
* the site is focused on a single topic
* SEO and social media tags as well as sharing buttons make the site easy to index and share / link to, which should lead to good ranking

Additional upsides:

* with a little additional build infrastructure we can include source code that is actually compiled (maybe even tested) like JUnit 5 does
* we an use all the ease of use and power of Asciidoc and the beauty of HTML 5 for our documentation

Downsides:

* it duplicates parts of the documentation (because it does not fully replace Javadoc)
* it is more effort to write and maintain than simple Javadoc

Is that worth the effort?

We could also go for middle ground and stipulate that every feature needs a page in those docs but that it can be a stub (much like [Wikipedia's](https://en.wikipedia.org/wiki/Wikipedia:Stub)):

* an introductory sentence or paragraph on the feature
* a note that this documentation is a stub
* link to related Javadoc

**Comment by nicolaiparlog** [comment]
After writing this, I realize I really like the idea of allowing stubs as it would allow us to get started earlier. So far I've been procrastinating on writing the docs for my disabling extensions but with stubs being ok, I could be done in five minutes.

Btw, whatever we'll decide on, I'll find a place to document it.

**Comment by smoyer64** [comment]
Or we could stub the documentation going the other way ... the javadocs
could describe parameters, returns, etc and regret to the asciidocs for a
longer description and examples.  So once you've learned an extension the
javadocs are all you need.

We should probably have a discussion about the disabling extensions as I
have some that overlap.   I started with @EnableIf and @DisableIf with a
predicate as the value and another String as a message template.   Then I
built everything else on that.   I have @EnableIfOs (and disable) in the
middle and specific annotations at the end.

This code is not done but I like the generic nature of the extension and
how you add new annotations with only their associated classes.   I'll get
what I have checked into the old selesy project so you can assess it.

On Jul 2, 2017 8:02 AM, "Nicolai Parlog" <notifications@github.com> wrote:

After writing this, I realize I really like the idea of allowing stubs as
it would allow us to get started earlier. So far I've been procrastinating
on writing the docs for my disabling extensions but with stubs being ok, I
could be done in five minutes.

Btw, whatever we'll decide on, I'll find a place to document it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/junit-pioneer/junit-pioneer/issues/19#issuecomment-312487790>,
or mute the thread

**Comment by nicolaiparlog** [comment]
I just created #66 to document the only existing, not superseded feature: An adaption of JUnit 4's `@Test` annotation.

At the same time I'm working on the last blockers for the documentation (code highlighting doesn't work yet, but will soon), so this issue and discussion is coming to a close soon unless someone speaks up against my proposal.  :neckbeard:

**Comment by nicolaiparlog** [comment]
Behold, for we have [external documentation](http://junit-pioneer.org/docs/).
