### ISSUE TITLE
Evaluate ShipKit

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#193]
We currently use ShipKit to deploy every commit. This works well enough, but there are a few things we may want to conisder:

* We move to GitHub Actions (see #192), which also offers shipping - why not consolidate the number of tools?
* The `version.properties` file in the top-level folder is annoying me (see #96); if we stick with ShipKit, I need to open an issue to see whether that could be changed.
* There's some POM-related duplication between `build.gradle` and `gradle/shipkit.gradle`, which is a bit annoying as well. Can this be fixed?
* ShipKit's documentation only shows Travis integration (which we move away from), but [mentions](https://github.com/mockito/shipkit/blob/master/docs/how-shipkit-works.md) "it's not difficult to use Shipkit with any CI" - how?
* ShipKit's approach of continuous deployment occasionally leads to spurious releases where we forgot to add `[ci skip-release]` to a commit message (not great to clutter them with that either) and the tool thought something changed when it didn't (e.g. 0.5.5 / 22f2571). That's not good.
* we occasionally had race conditions for `version.properties` where several PRs' changes of this file conflicted and needed to be updated
* For more to ponder, see #97, #171, and mockito/shipkit#867.

What does everybody think?

**Comment by nicolaiparlog** [comment]
Whatever we end up doing, we probably need to update [`CONTRIBUTING.md`-'s section on ShipKit](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#versioning).

**Comment by aepfli** [comment]
i am just taking a closer look into shipkit, and i think this tooling is fine. but i also think,  we do have some code duplciation. I mean we have configured a bintray plugin, which has a maven central sync. And (i might be wrong here) is maven central not oss.sonatype.org ?? because our publication is than redundant, if we really do have a sync from bintray setup to maven central.

Hence that i do not think we need the publication step in our build gradle. 

For the rest i will investigate, but if we stick to shipkit i think we need to stick to version.properties :)

**Comment by beatngu13** [comment]
My two cents:

I believe @nicolaiparlog once brought it up during a stream, if making a release is as easy as creating a tag, why struggle with CI skips etc. to avoid accidental releases? Especially since we as library maintainers somewhat still have the concept of releases that may bundle multiple patches—in contrast to e.g. web service development, where one almost always wants to continuously deploy. (See also #211 by @Bukama.)

Shipkit comes with a bunch of neat features such as the generated release notes (although I personally prefer the ["keep a changelog"](https://keepachangelog.com/) philosophy), but I'm not sure if these features are worth the aforementioned problems. In addition, the maintainers appear to rarely react to issues, at least to those where we are involved like https://github.com/mockito/shipkit/issues/867 or https://github.com/mockito/shipkit/issues/843.

Due to this, I tend to abandon Shipkit. Also because this probably makes it easier for new Pioneer contributors to grasp the release/deployment pipeline.

**Comment by nicolaiparlog** [comment]
Took a little time to research this a bit. Some comments...

Because I didn't think about this very much, beforehand, I hadn't quite realized that ShipKit is actually pretty cool and does a lot of useful but menial tasks (version bumps, tags, release notes, etc.,). :+1: I think it is worth keeping them automated.

I didn't check whether there's an alternative tool and instead wondered how we can make ShipKit work better for us. Here are my thoughts on some of my points above:

> * We move to GitHub Actions (see #192), which also offers shipping - why not consolidate the number of tools?

That's not a thing - GitHub Actions don't do Java releases to Bintray/Maven/etc.

> * There's some POM-related duplication between `build.gradle` and `gradle/shipkit.gradle`, which is a bit annoying as well. Can this be fixed?

There doesn't seem to be a canonical way to deduplicate this information. Maybe we can add code to `gradle/shipkit.gradle` that pulls these information out of `build.gradle` - either by parsing the file (yuck!) or querying some Gradle data structure. Or we can leave it, it's not that bad.

> * ShipKit's documentation only shows Travis integration (which we move away from), but [mentions](https://github.com/mockito/shipkit/blob/master/docs/how-shipkit-works.md) "it's not difficult to use Shipkit with any CI" - how?
>
> * ShipKit's approach of continuous deployment occasionally leads to spurious releases where we forgot to add `[ci skip-release]` to a commit message (not great to clutter them with that either) and the tool thought something changed when it didn't (e.g. 0.5.5 / [22f2571](https://github.com/junit-pioneer/junit-pioneer/commit/22f2571e9fe9e749ba7486317f0a49b5609bcfc3)). That's not good.
> 
> * we occasionally had race conditions for `version.properties` where several PRs' changes of this file conflicted and needed to be updated

We can circumvent this by triggering ShipKit manually, e.g.:

* from the local command line
* from CI by:
    * not touching `version.properties` in PRs
    * on release, updating `version.properties`, commit, tag, push
    * CI runs ShipKit only on tagged releases

Both approaches would make releases a quick but _deliberate_ action. This would prevent multiple releases on the same day as we often see due to the fact that merges often happen in "quick" succession on the same evening.

**Comment by aepfli** [comment]
> 

> > * There's some POM-related duplication between `build.gradle` and `gradle/shipkit.gradle`, which is a bit annoying as well. Can this be fixed?
> 
> There doesn't seem to be a canonical way to deduplicate this information. Maybe we can add code to `gradle/shipkit.gradle` that pulls these information out of `build.gradle` - either by parsing the file (yuck!) or querying some Gradle data structure. Or we can leave it, it's not that bad.

please see https://github.com/junit-pioneer/junit-pioneer/pull/213/files#diff-392475fdf2bc320d17762ed97109a121L144-L199 regarding that, this information is duplicated for no reason :) - so far not heavily tested, but it looks good on my bintray clone

**Comment by nicolaiparlog** [comment]
Wait what? Ok, then. :joy: What about stuff like the project description, or my blog URL, though? (Ok, we can ignore the latter.) And shouldn't the project site (https://junit-pioneer.org) be mentioned somewhere?

**Comment by aepfli** [comment]
> Wait what? Ok, then.  What about stuff like the project description, or my blog URL, though? (Ok, we can ignore the latter.) And shouldn't the project site (https://junit-pioneer.org) be mentioned somewhere?

![image](https://user-images.githubusercontent.com/9987394/78782320-232c7380-79a2-11ea-9401-a85a446d0c81.png)
i am pretty sure there is an overwrite somewhere for that, but it defaults to github

**Comment by aepfli** [comment]
https://github.com/bintray/gradle-bintray-plugin#buildgradle here we see which properties we can use to make it more junit pioneer-ish

**Comment by nicolaiparlog** [comment]
@aepfli, @Bukama, and I just had a call and we decided that ShipKit's feature set is valuable enough to keep it around. We would like to exert more control over the release process, though, and want to trigger them manually. We had a few ideas how this can be done:

* build locally on command line
* commits to master with a marker trigger a release
    * marker could be `[ci release]` in the commit message
    * marker could be `release: true` in `version.properties`
* tags on master trigger a release
    * each release could get its own "pre-release" tag
    * could reuse the same tag
* commits to a single, dedicated release branch

Expect follow-up comments that go into each variants' details. :smiley:

**Comment by Bukama** [comment]
> * build locally on command line

Discussion about this was short as it needs a full local setup including full knowledge of credentials for all tools for everyone who should be able to release. Also quite much manual steps which leads to much errors. So we discarded that option.

> * commits to master with a marker trigger a release
>   
>   * marker could be `[ci release]` in the commit message
>   * marker could be `release: true` in `version.properties`

The first of this options is quite the opposite of the current situation. But we see the problem on not being able to release without a dummy commit (whichs messes up history) in the following situation. As of now, we do the most of the PR / release releated work on tuesdays streaming session. When we merge a PR early in this session with the intention to do a release later in the evening after merging other PR and then a later PR, which we thought will be able to merge also in the evening is not mergeable (or it's getting to late) then we miss the oppurtunity to release (without a stupid dummy commit). 

The second option is similar but with a clear intention to do a release by modifing the `version.properties`. We discussed to place a dummy file inside `.infra` folder to be able to produce a commit on a "non productive` file but then we thought that we have to edit this file anyway when we do a major or minor release. @aepfli mentioned that shipkit will read and rewrite this file (after incrementing the version) anyway, so putting a keyword into it to start a release would be a clean way as after the release is done the keyword is cleaned up.

> * tags on master trigger a release
>   
>   * each release could get its own "pre-release" tag
>   * could reuse the same tag

These two options are similiar to those with a commit. Instead of pushing a commit we could push a tag. While the first option would quite mess up the tag list as shipkit will always tag its commit when doing the release, the second option points into the same direction as editing the `version.properties` file. Pushing a dummy tag like `weWantToReleaseNow` could trigger shitkit to release. Like editing the file shipkit could also remove this tag. Advantage of this solution above editing the `version.properties` is that you don't event need a text editor / IDE but only the command line to create and push a tag.

> * commits to a single, dedicated release branch

The idea behind this was to create a release branch and release everytime when there is a (merge) commit on this branch without the need of a specific keyword. So when we want to release we would merge master branch into the release branch and shipkit would be trigger. Problems with this solution are that a) the tags will be on release branch ab) the updates of release notes, docs, merge commits and especially `version property` would to go back to master in some way, either by (manually) cherrypicking them or by doing a full merge (including an additional commit) back into master. So we droped this possibility too.

> 
> Expect follow-up comments that go into each variants' details. 😃

Most probably we will do the tag thing or the `version.properties`. @aepfli willl evualte this and post his thoughts afterwards I think.

**Comment by aepfli** [comment]
i am not sure if we really need this ticket in the cleaner pioneers milestone, i do think this can be handled later too, and is not as important as other tasks. more like a nice to have

**Comment by nicolaiparlog** [comment]
Thanks @Bukama for going into detail on all the options. IIRC, I promised to write a bit of that and I didn't, so double-thanks. :)

Chewing this over, I think the reused tag is the best option:

* everything on CI (i.e. no local credentials)
* all information end up in `master` (instead of some release branch)
* no spurious commits

@aepfli Can you take a look at implementing this? As I see it, the key points are:

* the build step that triggers ShipKit must only be executed for a specific tag
* the build step must then remove the tag

Let us know know how it went. ;)

We should also take this opportunity to expand `CONTRIBUTING.md` with what we're doing here and a bit of why we do it this way. I can do that.

**Comment by aepfli** [comment]
the question is, do we really have to remove the tag? when i think closely about it, is a tag something which can only happens ones, so if we do not delete it, we will have a tag in there, which is not used, but which we can simply move forward, which would trigger the action. - will it be bad, if we have one wandering tag?

**Comment by Bukama** [comment]
> the question is, do we really have to remove the tag? when i think closely about it, is a tag something which can only happens ones, so if we do not delete it, we will have a tag in there, which is not used, but which we can simply move forward, which would trigger the action. - will it be bad, if we have one wandering tag?

tags are just labels for specific labels and therefore their name is unique, meaning you can only have one label with name `X` at one time. That's why we have to delete and recreate it.

**Comment by aepfli** [comment]
yeah but we do not need to delete the tag, we just simply would need to move it aka a wandering tag. but that is not needed any more, tag will be deleted in my proposal, i even cleanup the build a and it is cleaner now

**Comment by nicolaiparlog** [comment]
@aepfli's PR triggered a discussion about when to remove the `release` Tag.

@Bukama [wrote](https://github.com/junit-pioneer/junit-pioneer/pull/256#issuecomment-623061935):

> In my opinion it should be the last step of the process, so when the release was successful the tag is gone.

I [wrote](https://github.com/junit-pioneer/junit-pioneer/pull/256#discussion_r419383240):

> This means a broken release requires manual cleanup of the tag. Would that be a reason to perform this step much earlier, i.e. as the first one?

Discuss!

**Comment by nicolaiparlog** [comment]
I'd rather not use the tag for actual communication and while I agree that it appeals to our desire for symmetry to have the tag's lifetime encompass the build's lifetime, I think that doesn't have any actual value and the manual work it implies is annoying.

**Comment by aepfli** [comment]
As i am not on either side, i just want to put in one additional point, that if t inhe releaseTrigger is still in place, when you try to release, you will realize that there is an issue with the build, which forces some kind of investigation. It might be that somebody triggers release and leaves right afterwards, or forgets to wait for it to be finished. With the releaseTrigger tag still place, we for sure know that there was an issue. And it provides some kind of information, else this might get lost.

**Comment by Bukama** [comment]
@aepfli writes what my indent is of deleting the tag in the last step. We see that there was a problem we have to investigate. If we don't want to handle the risk of deleting the tag we would be back to commit messages I think.
