### ISSUE TITLE
Enable Checkstyle for the whole codebase

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#219]
Curently checkstyle is only testing "production code" as only the Gradle task "checkstyleMain" is actively integrated into the build pipeline. But there is also a task called "checkstyleTest' which would evaluate test sources. Or we do not evaluate the test sources by configuration

To enable this, we need to fix some issue with the test code. Currently the task is failing due to missing package-info.java within the test-packages.

As i have little to none knowledge about this topic, help from a person with deeper knowledge would be good for sure.

**Comment by nicolaiparlog** [comment]
Your PR #220 shows that we'd need some contortions to make the current CheckStyle settings work on our test code. Any chance we can configure a different configuration for the `checkstyleTest` class?

**Comment by aepfli** [comment]
good suggestion excluded test srcs for package info rule

**Comment by Bukama** [comment]
When I look at the checkstyle file than I'm wondering why we even check `Javadoc` if we allow everything to be empty.

```
<module name="JavadocMethod">
			<property name="allowMissingJavadoc" value="true" />
			<property name="allowMissingParamTags" value="true" />
			<property name="allowMissingReturnTag" value="true" />
			<property name="allowMissingThrowsTags" value="true" />
			<property name="allowUndeclaredRTE" value="true" />
			<property name="validateThrows" value="true" />
		</module>
		<module name="AtclauseOrder">
			<property name="tagOrder" value="@param, @return, @throws, @exception, @since, @author, @see" />
		</module>
		<module name="NonEmptyAtclauseDescription" />
```

Because when we allow missing Javadoc on our message, why do we enfore it for packages and enforce parameter descriptions? 

```
<module name="JavadocPackage" />

<module name="AtclauseOrder">
			<property name="tagOrder" value="@param, @return, @throws, @exception, @since, @author, @see" />
		</module>
		<module name="NonEmptyAtclauseDescription" />

```
For me this is an contradiction. As we are a public library we should enfore `Javadoc` at the public methods (which is the default - missing docs on (package) private methods will not be reportet as far as I know).

The `unused imports` and `avoid startimport` are mandatory - no question.

**Comment by nicolaiparlog** [comment]
I think it would be it great if we could configure the CheckStyle tasks for checking main code and test code with different configuration files instead of having to mentally evaluate the configuration and the suppression files to understand which checks apply to tests.

But since that doesn't seem to be possible without quite a lot of customization, we can just do what @aepfli proposes in #220.

**Comment by nicolaiparlog** [comment]
@Bukama I think your points are valid. I don't think it makes sense to discuss Sonar and Checkstyle checks separately, though, so let's widen the scope of #217 and talk about it there.

**Comment by Bukama** [comment]
> @Bukama I think your points are valid. I don't think it makes sense to discuss Sonar and Checkstyle checks separately, though, so let's widen the scope of #217 and talk about it there.

I think so too, so let us merge #220 and close this issue. Discussion about rules in total in #217.
