### ISSUE TITLE
RepeatFailedTest causes sporadically PreconditionViolationException

### ISSUE THREAD

**Issue by mp911de** [junit-pioneer/junit-pioneer#233]
A failed test repeated through `@RepeatFailedTest` sporadically leads to:

```
org.junit.platform.commons.PreconditionViolationException: Illegal state: required test method is not present in the current ExtensionContext
```

Link to a failed build: https://travis-ci.org/github/spring-projects/spring-data-mongodb/jobs/678085125

Reproducer: https://github.com/spring-projects/spring-data-mongodb/blob/46ab6b4c945fa5eef1acc000c9d9735a715c8f31/spring-data-mongodb/src/test/java/org/springframework/data/mongodb/core/messaging/ChangeStreamTests.java#L201

**Comment by nicolaiparlog** [comment]
Thanks for opening the issue, Mark. I'll look into it tomorrow.

**Comment by nicolaiparlog** [comment]
Immediate solution is simple: Remove [superfluous `@Test` annotation](https://github.com/spring-projects/spring-data-mongodb/blob/46ab6b4c945fa5eef1acc000c9d9735a715c8f31/spring-data-mongodb/src/test/java/org/springframework/data/mongodb/core/messaging/ChangeStreamTests.java#L200).

I'll post a longer explanation as soon as I'm done writing it. :grin:

**Comment by nicolaiparlog** [comment]
# What's going on?

The `@RepeatFailedTest` extension is mainly a [test template](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-templates), which means it becomes it's own container for the tests it generates and doesn't need an additional `@Test` annotation (just like `@ParameterizedTest`).

In the linked example, the test method is annotated with `@Test` _and_ `@RepeatFailedTest`, though, just like this example:

```java
@Test
@RepeatFailedTest(3)
void failsNever() { }
```

This means if the test is successful, it's executed twice:

![image](https://user-images.githubusercontent.com/6537432/80126340-40149980-8593-11ea-9cc8-f936993d44c1.png)

If it isn't successful, things get a bit more complicated. I said, this is extension is _mainly_ a test template. It's also a `TestExecutionExceptionHandler`, so it can catch exceptions and trigger an additional run:

```java
@Override
public void handleTestExecutionException(ExtensionContext context, Throwable throwable) throws Throwable {
	// this `context` (M) is a child of the context passed to `provideTestTemplateInvocationContexts` (T),
	// which means M's store content is invisible to T's store; this can be fixed by using T's store here
	ExtensionContext templateContext = context
			.getParent()
			.orElseThrow(() -> new IllegalStateException(
				"Extension context \"" + context + "\" should have a parent context."));
	repeaterFor(templateContext).failed(throwable);
}

private static FailedTestRepeater repeaterFor(ExtensionContext context) {
	Method repeatedTest = context.getRequiredTestMethod();
	return context
			.getStore(NAMESPACE)
			.getOrComputeIfAbsent(repeatedTest.toString(), __ -> FailedTestRepeater.createFor(repeatedTest),
				FailedTestRepeater.class);
}
```

Note the lengthy comment ([ha!](blog.codefx.org/techniques/documentation/comment-your-fucking-code)), which explains why we go from the failed test's context to its parent (in `handleTestExecutionException`) to access the store (in `repeaterFor`).  The implicit assumption is that `handleTestExecutionException` is called for a failed test that was generated from the annotated method (hence "go to parent!" ~> "get store").

Now, if the method is also annotated with `@Test` and it fails, this assumption is invalid: The extension is still a `TestExecutionExceptionHandler` and thus is called to handle that failed test, but since that test is the method itself (not a generated test), it's parent is a test class (not the test method) and thus `getRequiredTestMethod` in `repeaterFor` fails with the observed `PreconditionViolationException`.

# What can the user do?

Remove `@Test`. This is not optional because even if the extension would detect this case and rethrow the exception, the `@Test`-test would fail and thus break the build (regardless of what the `@RepeatFailedTest`-tests do).

# What can we do?

Two things come to mind:

* improve documentation to clarify that `@Test` is not needed
* add code that detects the case and provides a helpful error message

**Comment by mp911de** [comment]
Thanks a lot for the elaborate response. A validation failure would be indeed helpful. Meanwhile, I’m going to fix our tests.

**Comment by Bukama** [comment]
While working on this I noticed that there is already a warning for such misconfiguration. See my draft  #236

**Comment by nicolaiparlog** [comment]
Thanks for pointing out the warning, @Bukama, I did not know about it. For the sake of discussion, I copied it:

> Apr. 23, 2020 10:59:36 NACHM. org.junit.jupiter.engine.discovery.JavaElementsResolver logMultipleTestDescriptorsForSingleElement
> WARNUNG: Possible configuration error: method [void org.junitpioneer.jupiter.RepeatFailedTestTests$RepeatFailedTestTestCase.invalidConfigurationWithTest()] resulted in multiple TestDescriptors [org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor, org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor]. This is typically the result of annotating a method with multiple competing annotations such as @test, @RepeatedTest, @ParameterizedTest, @testfactory, etc.

That still doesn't conclusively answer, what we should do, though. I think the documentation update is obvious, but beyond that? Options:

* Nothing, this is a configuration error warned against in the documentation and by Jupiter, so users are on their own.
* Handle the case where `context.getRequiredTestMethod()` doesn't work by rethrowing the handled exception.
* Try to identify all failure cases (I think we can construct some, where `context.getRequiredTestMethod()` doesn't throw, but we still shouldn't do anything) and become "transparent"

Before we haven't decided, we can't adress the issue.

**Comment by aepfli** [comment]
I think a lot of this issue is related to the Annotation name `@RepeatFailedTest` does not sound like it is an annotation which represents a tests, it sounds more like an annotation which configures a test. Hence that maybe `@TestWithRetry` would be much easier to grasp, at least in my mind.

**Comment by nicolaiparlog** [comment]
Hm... It is common to specialize types "to the left", e.g. `List` and `ArrayList`. Also, would that argument not apply just the same to `@ParameterizedTest`? Maybe not because it "parameterize the test", but "this is a parameterized test" - maybe it should be `@RepeatedTest`, then? But then the "failed" part is missing...

**Comment by aepfli** [comment]
i still feel that `retry` more suggests that this is happening in an error case, than `repeat`. And i totally agree with `left typing` so i start another approach `@RetryingTest`. maybe this is just my lack of english knowledge. For me it just sounds way clearer than `@RepeatFailedTest`

**Comment by Bukama** [comment]
> I think a lot of this issue is related to the Annotation name `@RepeatFailedTest` does not sound like it is an annotation which represents a tests, it sounds more like an annotation which configures a test. Hence that maybe `@TestWithRetry` would be much easier to grasp, at least in my mind.

I think it's a problem of lacking documentation in first place. But I see your point, it's not very intuitve. I like the idea of renaming it to `@RetryingTest` or maybe something like `@RepeatTestWhenFailed`

**Comment by nicolaiparlog** [comment]
Getting closer to `@ParameterizedTest`, what about `@RetriedTest`?

@mp911de Since you ran into the issue, any idea which of these names (see last four comments) may have prevented the mistake?

**Comment by aepfli** [comment]
back to your suggestion, with putting it into a sentence like "this is a parameterized test", i think `retrying` fits perfectly as in `this is a retrying test`

**Comment by nicolaiparlog** [comment]
I like `RetryingTest`, particularly because it's in active voice. I updated #233 accordingly.

I decided against trying to detect failure cases because the Jupiter engine already warns and it seems difficult to figure these cases out reliably. Once #233 is merged, I consider this done.

@mp911de, if you're seeing this in time, I'd be interested to hear your opinion on the new name.

**Comment by mp911de** [comment]
No strong opinion on naming. It probably doesn’t make sense to rename and cause downstream effort as current proposal are mostly different but not significant more comprehensive.
