### ISSUE TITLE
Extend Beginner Guide in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#243]
I just stumbled across [opensource.guide](https://opensource.guide) and it looks like a great fit for our _If you're new to Open Source_ section in `CONTRIBUTING.md`. E.g.[_Opening a pull request_](https://opensource.guide/how-to-contribute/#opening-a-pull-request) (re [this comment](https://github.com/junit-pioneer/junit-pioneer/pull/239/files#r415049123)) would be something valuable to link to.

I think we should either:

* go through the guide to collect bits and pieces that are important to developing Pioneer or 
* create a list of things that are important to developing Pioneer and see where the guide can help

**Comment by Bukama** [comment]
> 
> I think we should either:
> 
> * go through the guide to collect bits and pieces that are important to developing Pioneer or
> * create a list of things that are important to developing Pioneer and see where the guide can help

I think we should go somehow both ways with keeping Pioneer in mind. For example the whole [How to Contribute to Open Source](https://opensource.guide/how-to-contribute/) section is great and we should link it the general beginners guide but maybe also in the particular sections. The information we've already added would maybe have help @Hancho2009 to avoid the "pr on master branch" thing, but maybe we can even do better.

Okay maybe not the part "How to find a project to contribute to?" does not fit to Pioneer, because the person has found the project already, doesn't he/she/d has? ;)

We (as maintainers) should also have a look at those organizing and formal chapters and see how our thoughts are doing (Do we align with the guide? Why do we have other opinions and which fit better for Pioneer? Have we forgotten some aspects that we should notice?).

We should take the time regardless if we update our docs or not. I'll try to do so (and maybe open a draft) during next week.

**Comment by nicolaiparlog** [comment]
I wrote a long blog post on extensions and there's also the JUnit 5 user guide. If anything's not covered between the two of those, e.g. the "I want to..." examples you give, they should be blog posts or something, but not hidden in our documentation.

**Comment by nicolaiparlog** [comment]
I went through GitHub's guide and considered these sections to be relevant:

* [Orienting yourself to a new project](https://opensource.guide/how-to-contribute/#orienting-yourself-to-a-new-project)
* [How to submit a contribution](https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution), particularly
    * [Opening a pull request](https://opensource.guide/how-to-contribute/#opening-a-pull-request)
* [What happens after you submit a contribution](https://opensource.guide/how-to-contribute/#what-happens-after-you-submit-a-contribution)

I would like to add them to our intro section together with a note that the entire guide is worth a read.

Any additional ideas?

**Comment by nicolaiparlog** [comment]
I like the idea of providing targeted how-tos as @Bukama describes them above. Articles that dissect existing extensions to explain how they work and why they're designed the way they are may also be interesting. If anybody's interested in writing something like that, I can help. Just open an issue.

Otherwise I will close this with #254.
