### ISSUE TITLE
Correct automatic module name of pioneer

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#251]
As of now the following entry inside the `MANIFEST` is created:

`"Automatic-Module-Name" to "org.junitpioneer"`

But URL is `https://junit-pioneer.org/`

Maybe @nicolaiparlog wants to add further information as in Discord he only asked to open an bishue about the topic :)

> nipafx: @Matthias / Bukama / bish Can you open a bishue about the automatic module name?

**Comment by nicolaiparlog** [comment]
Thanks for creating the issue. Just like packages, module names can't contain dashes, so _org.junit-pioneer_ is out of the question. But I wonder whether it should be _org.junitpioneer.xp_ (_xp_ = extension pack).

Because otherwise, if Pioneer launches other projects, their module name (e.g. _org.junitpioneer.foo_) would make it appear as if there's a super/sub relationship between these modules (just like people think of `org.junitpioneer.foo` as a subpackage of `org.junitpioneer`.

On the other hand, with _xp_, the module name would no longer be a prefix of the package name (not at all required, but a good practice and nice touch) and the internal moniker xp would leak into the public.

Opinions?

**Comment by nicolaiparlog** [comment]
Module and package names are drafted with the same process: Take a domain (example.org) and reverse it (~> _org.example_ for modules, `org.example` for packages). Package names are then often extended to appear as a deeper hierarchy (~> `org.example.foo`), which makes the module name a prefix of the package name.

That is not required at all by the module system, but it's aesthetically pleasing and if the module name were markedly different from the "top-level package" (no such thing in real life) than that's odd. Why is one so different from the other? In this case, if the module is called _org.junitpioneer.xp_, shouldn't then all packages have `org.junitpioneer.xp` as a prefix?

**Comment by Bukama** [comment]
Let's assume pioneer would have been a modularized project, next to others like the site. Then we would need an identifier for the project anyway.

Let's take a view from the GitHub page: organisation is "(org.)junit-pioneer" project is "junit-pioneer". So there's some type of duplication, but well you could say because we don't have a name for the extension pack project: Our package-names represent this too:
`org.junitpioneer.<missing projectname.>jupiter` (replace `jupiter` with `vintage` for Junit 4 stuff).

So we are missing that part in my opinion and I'm fine with just calling it `xp`. But then we should rename the packages inside the project too.

**Comment by nicolaiparlog** [comment]
Pointing to GitHub is a good idea. If we'd go with xp as the project name, it should then also be junit-pioneer/xp on GH, right? Eh... Three options:

1. Ignore the hierarchical module name "problem" and keep everything as is.
2. Acknowledge that the project is called XP and rename all the things to (org.)junit(-)pioneer(.|/)xp
3. Try some mix of junit-pioneer/xp on GitHub and in module/package name(s)

All of this seems more hassle than it's worth and I'm arguing for 1. If anybody strongly disagrees and makes a good point, I will reopen.
