### ISSUE TITLE
Add documentation about IDE specific configuration

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#281]
In #229 / #262 we provided additional IntelliJ specific configuration. Those needs to be documented.

**Comment by nicolaiparlog** [comment]
When I blabbered about documentation, I meant we could add the commit message configuration to Gradle-for-IntelliJ [as aepfli described](https://github.com/junit-pioneer/junit-pioneer/pull/262#issuecomment-634517898) and that we need to document that. I now realize that there's no point in configuring that, though, because the commit messages written in IntelliJ will never make it into the repo - squash&merge, right?
