### ISSUE TITLE
RepeatFailedTest fails if assumptions are invalid

### ISSUE THREAD

**Issue by rhwood** [junit-pioneer/junit-pioneer#291]
I have a project that I am converting from JUnit 4 to JUnit 5 and it runs tests both with and without the property `java.awt.headless == false`.

To make this work, we have a number of tests with this assumption as the first line of the test:
```
org.junit.Assume.assumeFalse(java.awt.GraphicsEnvironment.isHeadless());
```

That assumption works as intended to skip the test in JUnit 4 or JUnit 5 when annotated with `@Test`, but when annotated with `@RepeatFailedTest(2)`, that assumption causes a failure.

I would think that assumptions would not cause a failure.

**Comment by Bukama** [comment]
Hey, thanks for the issue,
indeed in it's current form the extension checks for failed assertions not failed assumptions. Maybe we should change this.

Another question as your description sounds like this:
Is `java.awt.headless` a system property or a system environment variable? If yes, maybe you want to have view at our [system property extension](https://junit-pioneer.org/docs/system-properties/) or the [environment variable extension](https://junit-pioneer.org/docs/environment-variables/)

**Comment by rhwood** [comment]
> Is `java.awt.headless` a system property or a system environment variable?

It is a property which is automatically set by the JDK (but can also be manually set) that is the system's indication it is in an environment where a GUI cannot be rendered. In my use cases, it is used to either allow a subset of the tests to be run (those that won't disturb you while doing something else), or to run on a system where the GUI does not work (a CI worker where X Windows has not been configured, or an SSH session without X windows redirection enabled). So it's not that I want to set the property, I want to skip certain tests if the property is true, but not skip them if the property if false.

That is merely the most common assumption I have to work with (I have some others where tests only run if a network address is reachable or specific hardware is detected.)

**Comment by Michael1993** [comment]
Since this is a fairly simple request I went ahead and created a PR for it.

I'm not sure if this issue needs discussion. According to the `@RetryingTest` documentation it should be used to retry tests that fail. But tests that do not meet assumptions never fail because they are not executed - therefore they should not be retried at all.

**Comment by Michael1993** [comment]
I've been thinking about this issue and I'm now less sure of myself.
When we are talking about tests, there are three parts, the preconditions, the actions and the assertions (or the given, when, then parts if you will). The actions and the assertions verify our own code, so we shouldn't retry them - we should only retry a test if it fails because of a precondition - which is exactly what an assumption is supposed to be...

So now I'm conflicted. What are your thoughts @rhwood?

**Comment by Bukama** [comment]
From @aepfli and my point of view the change is useful and so we decided to accept it by merging the PR (which also closes this issue)

**Comment by rhwood** [comment]
Sorry I missed the question.

If an assumption fails because a pre-condition was not met (say specific hardware is not available), I doubt that retrying it immediately would help (because the retry would occur faster than the hardware can become available), so it might be best to not retry if an assumption is not met instead of retrying it and failing the assumption every time.
