### ISSUE TITLE
Multiversion build with different JUnit versions

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#296]
Currently our extension is built for version 5.5.2, but what if somebody with version 5.5.0 or 5.6.2 wants to use JUnit Pioneer. Do we know if this is possible? We should think of experimental builds to cover most JUnit5 Versions out there. So we know, if our application at least builds with those versions, and if the tests are passing.

As soon as there is a new version, we should also add it to our build pipeline, So we can ensure backwards and forward compatibility. Ideally we run this just on master, but we can also think of doing this for pull requests, but for pull requests, i do not see much benefit for this. What do you think @junit-pioneer/junit-pioneer-team ?

**Comment by aepfli** [comment]
https://github.com/junit-pioneer/junit-pioneer/actions/runs/167772059

 as there is an pr open from myside already, because i found it interesting there are also the action above to take a look at :)

**Comment by nicolaiparlog** [comment]
First of all, very good point, we should strive to be compatible with as many JUnit versions as possible. Thinking of it, I think the docs don't even say as much. A policy like "be compatible with all versions in the range from [required; newest]" would make a lot of sense. Maybe this is a good time to discuss and possibly document.

Regarding your specific questions, I'm not sure on which branches to build this because:

1. building for many versions takes a while I assume, so on PRs this would make feedback unacceptably slow
2. since we're only developing in branches, PRs should be built against all versions, so we can spot problems before we merge them
3. since any new JUnit 5 versions could break Pioneer, we need to run master against newest versions as soon as they are released

Yes, this is a nice hodgepodge of contradictions. Not sure what the best course of action would be.

**Comment by Bukama** [comment]
I like the idea and we could use this argument also to upgrade to the newest Pioneer version also (I personal don't see so much obstacles to upgrade a JUnit Jupiter version in comparison to something like Hibernate where you are bound to JPA-Specc etc.) - but that's another topic.

For me it's okay to run every PR against all other JUnit versions (but should do this only on LTS java versions). If we are honest to ourself: the only time where the duration of builds is somehow "annoying" is when you are "live coding" like in the streams, but that's not the regular thing.

> 3. since any new JUnit 5 versions could break Pioneer, we need to run master against newest versions as soon as they are released

That only means we have to update the matrix in the script after there's an JUnit release. I think that's fine.

**Comment by aepfli** [comment]
as we all agree here, i remove the label in discussion, and i will continue with my implementation
