### ISSUE TITLE
DefaultLocaleExtension/DefaultTimeZoneExtension do not need BeforeAllCallback or AfterAllCallback

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#308]
The `DefaultLocaleExtension` and the `DefaultTimeZoneExtension` implement the `BeforeAllCallback` and `AfterAllCallback` interfaces. Those seem redundant and probably should be removed.

There is no major observable difference in behaviour if we remove the callbacks.

**Comment by nicolaiparlog** [comment]
Thanks for spotting this, @Michael1993! This is indeed a weird way to write the extensions and after you brought it up, I wondered for a while whether it was intentional. If it was, the intention is lost to time as I can see no reason in doing the same thing in before/afterAll and before/afterEach. The only difference I could observe is whether a misconfigured extension on a class fails the entire class (i.e. container) or each individual test method, but that should not matter to users. I'm in favor of simplifying this.
