### ISSUE TITLE
Where's the module-info.java file?

### ISSUE THREAD

**Issue by sormuras** [junit-pioneer/junit-pioneer#314]
Add a module descriptor to the root of the JUnit Pioneer JAR file. Something like:

```java
module org.junitpioneer {
  exports ...
  requires ...
}
```

**Comment by Michael1993** [comment]
JUnit Pioneer currently uses Java 8 from [the build.gradle](https://github.com/junit-pioneer/junit-pioneer/blob/master/build.gradle.kts#L15):

```
java {
	sourceCompatibility = JavaVersion.VERSION_1_8
}
```

Sadly, no `module-info.java` in Java 8. 😭

**Comment by Michael1993** [comment]
What we _can_ do:
* [ ] Upgrade to Java 11
* [ ] Create a new gradle profile with Java 11 and set up the Java 8 build to ignore the `module-info.java`

Optionally the source code can be updated to Java 11 and compiled back to Java 8 byte code with something like [Jabel](https://github.com/bsideup/jabel)

**Comment by sormuras** [comment]
Or use https://github.com/moditect/moditect

**Comment by nicolaiparlog** [comment]
Still not convinced module declarations make too much sense for test code, but since it doesn't appear to hurt anyone (I infer from JUnit 5 having them for quite some time now), we can look into this.

Regarding the build, it appears easiest to me to make Java 11 the default/release build (with `--release 8`) and turn Java 8 into a "compatibility build" (like 14) where we exclude `module-info.java`.

**Comment by Bukama** [comment]
When switching to modules I suggest to offer the PioneerTestKit and Assertions as an own module, so user can write their own extensions and use our Testkit / Assertions for it.

**Comment by nicolaiparlog** [comment]
I did the simplest thing by adding a `module-info.java` and bump the source compatibility in Gradle:

```diff
diff --git a/build.gradle.kts b/build.gradle.kts
index f6cc08a..77fa80e 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -13,7 +13,7 @@ group = "org.junit-pioneer"
 description = "JUnit 5 Extension Pack"
 
 java {
-	sourceCompatibility = JavaVersion.VERSION_1_8
+	sourceCompatibility = JavaVersion.VERSION_11
 }
 
 repositories {
diff --git a/src/main/java/module-info.java b/src/main/java/module-info.java
index 6b1b170..f0c6bce 100644
--- a/src/main/java/module-info.java
+++ b/src/main/java/module-info.java
@@ -1,2 +1,9 @@
-module $MODULE_NAME$ {
-}
\ No newline at end of file
+module org.junitpioneer {
+	// could be `transitive`, but that's its own discussion
+	requires org.junit.jupiter.api;
+	requires org.junit.jupiter.params;
+
+	exports org.junitpioneer.vintage;
+	exports org.junitpioneer.jupiter;
+	exports org.junitpioneer.jupiter.params;
+}
```

Result:

```sh
nipa 🤡 JUnit-Pioneer :: ./gradlew build

> Configure project :
  Building version '0.9.1' (value loaded from 'version.properties' file).

> Task :compileJava FAILED
/home/nipa/code/JUnit-Pioneer/src/main/java/module-info.java:3: error: module not found: org.junit.jupiter.api
        requires org.junit.jupiter.api;
                                  ^
/home/nipa/code/JUnit-Pioneer/src/main/java/module-info.java:4: error: module not found: org.junit.jupiter.params
        requires org.junit.jupiter.params;
                                  ^
2 errors

FAILURE: Build failed with an exception.
```

It seems to take more time and Hirnschmalz than I'm willing to spend on this task (because I'm still not convinced test modules are worth it). We welcome PRs on this, but we may not merge one without bumping the major version (talking post 1.0) and that may have to be a discussion on its own.

**Comment by Bukama** [comment]
Gimme time, but I think I'm motivate to get in touch with the module-system myself for the first time.

**Comment by sormuras** [comment]
@Bukama This documentation could help: https://guides.gradle.org/building-java-9-modules/
