### ISSUE TITLE
Decide on what dependencies we should allow

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#33]
LIke the JUnit 5 project, I think limiting the dependencies in the core project is a worthwhile goal.  At this point I'd really only argue strongly for JSR-305 annotations (current GAV is com.google.code.findbugs:jsr305:3.0.1).

For tests and infrastructure, I don't tend to be as militant ... should we allow the following?

-   AssertJ
-   Mockito
-   JaCoCo

(I'm sure this list will grow as we do!)

**Comment by jbduncan** [comment]
I think for tests and infrastructure, we should simply depend on stuff when we need them. 

AssertJ and Mockito sound like good starting testing libraries to me. Although, I do wonder if it's worth adopting Google Truth instead of AssertJ.

Yeah, I know that Truth is not as full-featured as AssertJ, but I believe that the assertion API it provides is overall cleaner than AssertJ's. And if we encounter any pain points for which we need to write our own custom assertions, we can be Good Samaritans and give feedback to the Truth team to help the library improve!

(See https://google.github.io/truth/comparison for some examples of how it compares to AssertJ and others.)

**Comment by nicolaiparlog** [comment]
@smoyer64 Thanks for opening this issue. Once we settled on something, we should document the decision. I guess the README is the best place for now...

> I'd really only argue strongly for JSR-305 annotations

For nullability I assume? My approach would be to apply `@NonNull` (or whatever it's called) to the root package and use `Optional` everywhere else. :wink: Are there any other annotations you'd wan to use?

> For tests and infrastructure, I don't tend to be as militant ... should we allow the following?
>
> * AssertJ

Yes.

> * Mockito

Definitely.

> * JaCoCo

Never used it. I think JUnit reported problems with code coverage. Should we open a separate issue for that?

@jbduncan I had a quick look at Google Truth and it indeed looks very similar to and maybe even slightly better than AssertJ. Of the examples you linked to, I particularly liked the message bearing commands better. But this project's goal is to stay close to JUnit 5 for easier work across code bases. Using a different assertion library would move us away from that (and not by a little) and since I am very happy with AssertJ a switch to Truth would not offset that downside.

**Comment by jbduncan** [comment]
@nicolaiparlog That's fair enough (regarding Truth). Consistency with JUnit 5 is a laudable goal, so I'm happy for pioneer to use AssertJ as well.

**Comment by nicolaiparlog** [comment]
@smoyer64 Regarding JaCoCo, I just stumbled upon #28, so I think we should follow up on that there. Assuming you're still fine with limiting ourselves to AssertJ and Mockito, I'd start documenting that.

**Comment by smoyer64** [comment]
@nicolaiparlog - Dealing with code coverage in #28 is fine.  I'll comment on my experience with JaCoCo in that issue.  More importantly, I'd like to make sure we don't forget about static code analysis and JSR-305 annotations.  I started this issue with that and should have put it in the bullets.  So can we make this issue about AssertJ, Mockito and JSR-305?

**Comment by nicolaiparlog** [comment]
Oh, indeed I was just looking at the bullets. Yes, we can include JSR 305 but at some point we have to decide how to handle `null`. As I said, I'm in favor of using `Optional` "everywhere" and thus never allowing anything valid to be represented by `null`, which somewhat diminishes the value of annotations related to nullability. But we can discuss that in some separate issue. For now, let's include the following:

* AssertJ
* Mockito
* JSR-305

**Comment by smoyer64** [comment]
I agree that all return values should be ```Optional``` if they might not be present.  Annotating these methods with ```@NonNull``` would be repetitive but it also instructs FindBugs to make sure the method *can't* return null.  You'd obviously never annotate a method with anything else (such as ```@CheckForNull```.  I'm of the opinion that parameters shouldn't use ```Optional``` - it just seems to add a lot more boilerplate code to the method body.  So I do use these annotations for parameters.

Methods that return ```Optional``` should also be annotated with ```@CheckReturnValue``` except in the rare instance where you're calling a method for its side-effect (since pure functions don't have side-effects).

I should also add that I'm not great with my consistency (yet) and am still learning how to specify the "contract" such that static analysis tools do the most good.  Obviously, including JSR-305 annotations in the code implies we're executing Findbugs but that's a topic for another issue (it won't become a dependency of the project).

FindBugs and JSR-305 both seem, if not dead, unmaintained.  Bill Pugh (the UMD professor who created FindBugs) has [promised on HN](https://news.ycombinator.com/item?id=12885549) but that seems to be his only communication on either in the last 4-5 years.  I'd be a big fan of JSR-305 creating a standard set of annotations for code analysis but when I approached the JCP about transferring that specification to our JUG I was told that Bill Pugh would have to transfer ownership.  All this is a long way of asking whether we should consider [SpotBugs](https://spotbugs.github.io/) instead.

**Comment by nicolaiparlog** [comment]
I just opened #50 - can you make your argument for a code analysis tool there`

**Comment by nicolaiparlog** [comment]
And for discussions around `null` I just opened #51.
