### ISSUE TITLE
Adding .gitattributes

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#341]
To make JUnit Pioneer (and spotless) work more seamlessly, we should consider adding a `.gitattributes` file.
Specifically I am thinking about adding an option for line-endings (e.g.: `* text eol=crlf`).

**Comment by Bukama** [comment]
What are the consequences for OS that have another line ending / break?

**Comment by Michael1993** [comment]
Well, I just tried on Windows 10, and spotless changed all line-endings to LF.
Which added all files to the commit. 🤦 
If we had `.gitattributes` this would not be an issue.

**Comment by Bukama** [comment]
> I just tried on Windows 10, and spotless changed all line-endings to LF.
> Which added every file in the project to the commit as "changed". 🤦
> If we had `.gitattributes` this would not be an issue.

Hmm never had this issue, but I have configured my Git to checkout LF for system, but keep the original LF for commiting/check in

**Comment by Bukama** [comment]
> > I just tried on Windows 10, and spotless changed all line-endings to LF.
> > Which added every file in the project to the commit as "changed". 🤦
> > If we had `.gitattributes` this would not be an issue.
> 
> Hmm never had this issue, but I have configured my Git to checkout LF for system, but keep the original LF for commiting/check in

As the [Git documentations says](https://git-scm.com/docs/gitattributes), that's because:

>  Note that setting `core.autocrlf` to `true` or `input` overrides `core.eol`

**Comment by dwalluck** [comment]
To make a long story short, if you're already on Linux or macOS, then you shouldn't notice any change with this. But, if you're on Windows, then this will fix the build for you and stop changing the newlines on all the source files (which for me are not the files that are checked out, but the ones that end up in the build tree).

Since even people on Windows don't want this Git "feature", I wonder if anyone does. The only thing to look out for is that if you ever need a Windows-specific file, you should add the file (or file extension) to the `.gitattribues` file. But, I don't see any such files in junit-pioneer.

**Comment by nicolaiparlog** [comment]
Thanks @Michael1993 and @dwalluck for bringing this up. See #347 for my proposed solution.
