### ISSUE TITLE
Migrate eskatos/gradle-command-action -> burrunan/gradle-cache-action

### ISSUE THREAD

**Issue by vlsi** [junit-pioneer/junit-pioneer#349]
It unlocks fine-grained remote build cache with GitHub Actions backend
(=faster builds), and it adds error markers
(e.g. compilation errors right in the commit diffs)

See https://github.com/burrunan/gradle-cache-action#gradle-cache-action

The major improvements over gradle-command-actions:
🚀 Gradle remote build cache backend (pulls only the needed entries from GitHub cache)
🎉 Support multiple remote caches via gradle-multi-cache (e.g. GitHub Actions + S3)
👋 Simplified configuration (action name + gradle command is enough for most case)
👾 Less space usage (GitHub imposes overall 5GiB limit by default, so cache space matters)
🔗 Link to Build Scan in build results
💡 Gradle build failure markers added to the diff view (e.g. compileJava or compileKotlin markers right in the commit diff)

See sample usage in https://github.com/junit-pioneer/junit-pioneer/pull/325

**Comment by Bukama** [comment]
@aepfli @beatngu13 Please take a look at this.

**Comment by beatngu13** [comment]
First of all: Sorry for the massive delay and thank you for creating #325.

While the improvements you have listed sound indeed reasonable and helpful, I don't feel like we currently have issues with these things. Therefore, I would personally prefer to stick with the more widely-used `eskatos/gradle-command-action` (also because it stems from a Gradle employee), at least for now.

Other opinions?

**Comment by nipafx** [comment]
I don't feel qualified to have an opinion, but as I understand @beatngu13, there's to pressing reason to switch. I will close this issue (for now), but if things change and [burrunan/gradle-cache-action](https://github.com/burrunan/gradle-cache-action#gradle-cache-action) becomes more advantageous, we can reopen.

@vlsi please feel free to let us know when you think we should reopen.
