### ISSUE TITLE
Move SuiteEngine to a pioneer sub-project

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#35]

**Comment by Bukama** [comment]
After reading the linked (and from that one further linked) issue(s) in JUnit repository it seems that it will at some point get included in JUnit itself. When the general availablity to define dynamic "test suites" [JUnit-Jupiter-744](https://github.com/junit-team/junit5/issues/744) there should be an own annotation be introduced [JUnit-Jupiter-330](https://github.com/junit-team/junit5/issues/330).

The only question is when: It was in the backlog for the last versions and is again in the 5.7 one, but @sbrannen already mentioned that he's not sure if it will make its place.

> sbrannen on Feb 3rd 2020
> No, there is unfortunately no update on the status of this other than that it is slated for the 5.7 backlog, which designates an interest in getting it implemented in time for 5.7 GA but without any guarantees for inclusion in 5.7.

Regardless of that I think we can close this issue. What do you think @nicolaiparlog ?

**Comment by Bukama** [comment]
As you, @aepfli , were promoted: What are your thoughts?

**Comment by aepfli** [comment]
this is a rather old issue, and a lot of discussion going on :) - too much for me to read, at this time of the day. :) - will try to check in the next days. but it seems like i have to aggregate some background knowledge to actually put together some thoughts on this.

**Comment by nipafx** [comment]
It's not entirely clear to me what this is about, but it looks like (a) there hasn't happened a lot here since March 2017 (remember a world before COVID?!) and (b) junit-team/junit5#744 has this covered. I'm thus closing this issue.

If I missed anything and it makes sense to further consider this, feel free to leave a comment and we can reopen, but please include a description of what exactly this is about.
