### ISSUE TITLE
Pioneer 1.1.0 fails quality gate

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#385]
The current version of the expansion pack (1.1.0) failes the quality gate, because not reaching 80% (but only 75,76%) code coverage:

https://sonarcloud.io/dashboard?id=junit-pioneer_junit-pioneer

**Comment by beatngu13** [comment]
I'm not a SonarCloud admin for Pioneer, but since our token is public (🙃), I was able to write some API queries that (i) copy the default "Sonar way" QG and create new one called "Pioneer way", (ii) set it to require only 70 % coverage on new code and (iii) select it as QG for Pioneer.

Could someone please re-run the build? Then the problem should be gone.

**Comment by Michael1993** [comment]
Lowering quality thresholds when we fail to meet them or update our codebase to pass the thresholds? Hm. 🤔

**Comment by beatngu13** [comment]
IMHO fixing `master` has higher priority, the error-causing PR shouldn't have been merged in the first place (I believe it was: https://github.com/junit-pioneer/junit-pioneer/pull/361#issuecomment-733200767).

Now that `master` is stable again, we can easily address the underlying issue—without pressure—by adding missing tests and/or update the SonarCloud config.

**Comment by Michael1993** [comment]
My "investigation": SONAR considers our code coverage low because of getters, `hashCode` and `equals`. Which means we do not use those methods. I thought: why not delete them?
Because we provide instances to `IssueProcessor` implementations.

It seems we have three choices:
1.) We create unit tests for the getters, `hashCode`, `equals`.
2.) We configure SONAR to ignore those methods and consider them "good enough". (I do not like this approach, since it's lowering the bar).
3.) We add tests for those methods in the integration testing of `IssueProcessor`/`IssueExtension`.

I'm going to go ahead with the 1st approach in #386 - feel free to add your input here or on the PR.

**Comment by beatngu13** [comment]
@Michael1993 thanks for creating #386! Will try to do a review ASAP.

Regarding your investigation: I'm advocating _against_ writing tests for simple getters for the sole purpose of increasing test coverage. (`hashCode`/`equals` maybe.) I'd rather update the QG and/or rules set.

In any case, we shouldn't dogmaticly follow Sonar's suggestions. One case easily mark warnings as false positives or ignore them via the UI, and often there are good reasons to do so.

**Comment by Bukama** [comment]
Of course option 1.

**Comment by Bukama** [comment]
Damn GH, i only wroted `related` not `closes` :(

CC up to 93%.
getter/setters etc. still up.

**Comment by Michael1993** [comment]
I've been thinking about it and I've changed my mind. I think creating unit tests for generated code is unnecessary. After all, we generate these methods because they are simple enough to be generated. I think we should exclude them from code coverage.

**Comment by scordio** [comment]
About `equals` / `hashCode`, although they are usually generated I'd still suggest testing them, not manually but using [EqualsVerifier](https://jqno.nl/equalsverifier/).

**Comment by Bukama** [comment]
> I've been thinking about it and I've changed my mind. I think creating unit tests for generated code is unnecessary. After all, we generate these methods because they are simple enough to be generated. I think we should exclude them from code coverage.

But the test helps that if you add/remove an attribute, but forget to update (regenerate) the hash/equals/toString method either

**Comment by nipafx** [comment]
I don't have a strong opinion on this. Testing `equals`/`hashCode` is not the most valuable thing to do (particularly not by hand), but it's not without value either. I wanted to give [EqualsVerifier](https://jqno.nl/equalsverifier/) a shot anyway and this looks like a good opportunity. Curious to see the PR. 😁

**Comment by nipafx** [comment]
While going over the test coverage, I saw that `PioneerException` is nor used. Why does it exist? @Michael1993 You introduced it in 2d1e63d34, so you may know. 😁

**Comment by nipafx** [comment]
Hah, #417 lowered uncovered lines from 44 to 30 - great success!

**Comment by beatngu13** [comment]
> While going over the test coverage, I saw that `PioneerException` is nor used. Why does it exist? @Michael1993 You introduced it in [2d1e63d](https://github.com/junit-pioneer/junit-pioneer/commit/2d1e63d34a1433faa35238fd50ec1116afe66a5d), so you may know. 😁

I assume it was because of [this rule](https://rules.sonarsource.com/java/RSPEC-112), Sonar doesn't like `RuntimeException`s…

Also, should #417 close this issue? There seems to be no consensus about:

* Tests for `equals`/`hashCode`?
* Tests for getters/setters?
* Tweak quality gate?
* How to deal with Sonar's complaints in the future, when a corresponding PR check fails?
