### ISSUE TITLE
Improve `@RetryingTest`: offer suspend attribute or similar to configure pauses between reruns

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#407]
Related to #355 

User should be able to specify a "cooldown" period between failed test re-runs. Example:

```java
@RetryingTest(value = 3, suspendForMs = 1000)
void test() {
  Assertions.fail(); // should wait 1 second (1000 ms) between runs
}
```

Alternatives/additions:
```java
@RetryingTest(value = 3, suspend = 1, suspendUnit = ChronoUnit.SECONDS)
void test() {
  Assertions.fail(); // should wait 1 second (1000 ms) between runs
}
```

Adding other suspend modes, e.g.: `RANDOM`, to wait a random amount of time between 0 and `suspend`.
```java
@RetryingTest(value = 3, suspend = 1000, suspendUnit = ChronoUnit.MILLIS, suspendMode = SuspendMode.RANDOM)
void test() {
  Assertions.fail(); // should wait between 0-1 second (0-1000 ms) between runs
}
```

Alternative:
```java
@RetryingTest(value = 3, suspendForMs = 1000, suspendForMsFactor = 400)
void test() {
  Assertions.fail(); // should wait 1-1.4 second (1000-1400 ms) between runs
}
```

**Comment by nipafx** [comment]
Please rename `suspend` to `suspendForMs`, so the unit is included in the attribute's name for better readability.

**Comment by slawekjaranowski** [comment]
what do you think about providing some random suspend value?

we can have `suspendForMs` with minimal suspend time value
and second property `suspendForMsFactor` (or similar)  

behavior
 - only set `suspendForMs` - wait this time
 - only set `suspendForMsFactor` wait `Random.nextInt(suspendForMsFactor)`
 - set `suspendForMs` and `suspendForMsFactor` wait `suspendForMs + Random.nextInt(suspendForMsFactor)`

**Comment by Michael1993** [comment]
@slawekjaranowski I'm curious - what's your use case? Seems very specific.

**Comment by slawekjaranowski** [comment]
No specific case - just proposition for more elastic configuration

**Comment by Michael1993** [comment]
Okay, I updated the original issue with an approach that should cover your proposal and we can have a discussion about it.

My personal take on it is that if a retrying test needs to wait, then it's not a big difference if it has to wait a specific or a random amount of time. Do you have a use case where this would be useful?

**Comment by slawekjaranowski** [comment]
When test depends on external resource (eg. web service) and project is developed by many developers, run on many ci systems it can happen that test from each environment will retry in the some similar time.

Of course I think about some of IT, system tests - unit test shouldn't depends on external resources.

**Comment by mathieufortin01** [comment]
Hi, just discovered this project. This feature seems an adequate candidate to dive into the code base. so, if thats ok, some questions/comments:
- I would go with `suspendForMs`. Splitting into value and unit has some flexibility, but feels like its not really needed for tests (is there a need to suspend for minutes/hours/etc ?)
- Do I include the fuzzy/random factor? If yes, I would propose a randomization factor between 0 and 1. For example, `suspendForMs = 1000, suspendRandomFactor = 0.5` would set a random number between 500ms and 1500ms. Thinking about it a little more, if theres a need for randomization, theres probably a need for exponential backoff (with randomization). But wondering if theres really a case for that in a test context...

**Comment by nipafx** [comment]
Hey @mathieufortin01, thanks for offering to contribute. 👍🏾 You can definitely give it a go. I'm not 100% sure what would be the best way to implement this, so I recommend to start with a proof of concept (basic implementation and a few demos/tests to demonstrate) without polish (no documentation, tests don't need to assert anything if that turns out to be complicated) and open a draft PR with that, so we can take a look.

On your two points:

* I agree, go with `suspendForMs`.
* While reading that I also thought about exponential backoff, shortly before you brought it up. 😆 I think that that would be a natural expansion of this concept. And while implementing randomization and backoff would probably be fairly straightforward once the basics are done, they also require documentation and tests, which would make this change much larger. Let's go without that for the moment, so we can get a POC and eventually a merged PR reasonably soon and then expand on that in a separate PR.

PS: We're not always timely with out replies to issues and PRs, so best prepare for that. 😊
