### ISSUE TITLE
Evaluate Shipkit auto versioning vs. gradle git version plugin

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#442]
We currently use shipkit-auto-versioning plugin for maintaining our versions. It offers a clean way, to define versions, but the versioning itself seems to be a little bit odd, as the patch versioning is defined by number of commits. 

On the other hand there is https://github.com/palantir/gradle-git-version which from the outside suits our versioning better.
It defines the version based on the last tag. It does not offer auto version increase like the the shipkit autoversioning plugin, but based on our usage this would be fine.

How we release with shipkit:
- we trigger a build
- it autodetects version
- it tags and uploads

How would we release with gradle git version
- we create a tag
- which will trigger a build
- which will create release and upload

I might miss here some functionality, or some connection between the changelog and the version plugin. But it might be worth investigating.

Befor https://github.com/junit-pioneer/junit-pioneer/issues/410 it would not have been possible to switch, as shipkit was too tightly coupled but the new version offers us more flexibility, and would allow us, to exchange just to version part to something, which fits our workflow in a better manner

**Comment by Michael1993** [comment]
We have two options:
 ### 1.) We switch to `gradle-git-version`

This is straightforward, but makes our release a bit clumsier.

### 2.) We send a PR to Shipkit auto-versioning plugin

We *could* convince the Shipkit team to update/amend their auto-versioning plugin with a setting that fits our use-case. This would mean a long process of opening an issue, having a discussion, extending their plugin, etc. This is a bit more involved but it would be much more comfortable from Pioneer's standpoint.

**Comment by nipafx** [comment]
I looked into this and here are some thoughts:

* Shipkit seems to no longer write to `docs/release-notes.md`, but it looks like [it can be configured](https://github.com/shipkit/shipkit-changelog#orgshipkitshipkit-changelog-plugin) (see parameter `outputFile`), so we should probably do that
* the `generateChangelog` task needs to know the previous revision - without [the auto version plugin](https://github.com/shipkit/shipkit-auto-version) we'd have to either write to that file on every release (to put the current version there) or provide it some other way (environment variable?)
* the auto version plugin only does its "determine the next version" thingy when Gradle's `project.version` property isn't set. Maybe we can set it from an environment variable?

**Comment by nipafx** [comment]
Addendum to the last point: Contrary to what [the documentation](https://github.com/shipkit/shipkit-auto-version#implementation-details) seems to suggest, the file `version.properties` is always needed, even if the property is specified on the command line.

**Comment by nipafx** [comment]
If [shipkit-auto-version](https://github.com/shipkit/shipkit-auto-version) would increase the patch version sequentially, we'd be all set. I opened [an issue](https://github.com/shipkit/shipkit-auto-version/issues/72) and [a PR](https://github.com/shipkit/shipkit-auto-version/pull/73) for that - let's give it some time to see where those go.

**Comment by nipafx** [comment]
Well, not _all_ set. The website still won't build because Shipkit no longer writes the previous version to `version.properties`. That's a good thing because a release no longer result in a commit, but it means we need to find another way for the site build to determine project versions. Ideas:

* use `git log` to determine the version
* add [parameters to the release workflow](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/), specifically the next version - we can then pass it to the website build (while writing this, I realize that it's not a good solution because as soon as there are multiple projects that can trigger the build, not all versions could be passed)

Looks like `git log` then...

**Comment by nipafx** [comment]
Last note on the release notes: While it's possible to configure the output file, there seems to be no machinery that commits it back to the repo. Without that, our release notes will stay as they are (i.e. outdated). I hence propose to remove them and rely on GitHub releases for change-interested users. (NB: The website's "Changes between versions…" title card already links to [the latest releases](https://github.com/junit-pioneer/junit-pioneer/releases).)

**Comment by Bukama** [comment]
Can't we execute some shell script / Github action scripting outself? At my work I created a Jenkins pipeline (written in Groovy as Jenkins Pipelines are Groovy) which
* check outs the project
* increses the projects version
* commits this
* creates a git tag with this version
* pushes this
* deploys the whole thing to our central artefact repository

**Comment by nipafx** [comment]
I prefer to keep this in the build tool. First, because I think it's one of its core tasks, but also because it's then available locally (unlike GitHub Action without additional effort) and across all OS (unlike a script). We'd also need to recreate a lot of functionality that's already there (e.g. parsing commits to create release notes, GitHub API interaction to populate a release, artifact repo API to publish a repo).
