### ISSUE TITLE
Annotations like @SetSystemProperty are not inherited

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#448]
The following test fails:

```java
@SetSystemProperty(key = "set prop A", value = "new A")
class SuperClass { }

@Nested
class TestClass extends SuperClass {

	@Test
	void shouldSetSystemPropertyToValue() {
		assertThat(System.getProperty("set prop A")).isEqualTo("new A");
	}

}
```

Unless I'm missing something, it stands to reason that it should pass because it should inherit the annotation from the super class. Am I missing something?

**Comment by Michael1993** [comment]
This should be a very simple fix, no? Just add the missing [`@Inherited`](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Inherited.html) annotation on our annotations. Or am *I* missing something?

**Comment by Michael1993** [comment]
Yeah, I just checked, this is a very simple fix.

**Comment by Michael1993** [comment]
Part of the solution for this should include tests that verify the new behaviour.

**Comment by beatngu13** [comment]
As pointed out by @Michael1993 in #449, there are more annotations – besides the environment variable and system property extensions – we should consider making `@Inherited`.

I believe this only makes sense for annotations targeting `ElementType.TYPE`, since we are dealing with test base classes. Searching for `ElementType.TYPE` yields:

- `@DefaultLocale`
- `@DefaultTimeZone`
- `@Issue`
- `@Stopwatch`

Plus all the `@Reads*`/`@Writes*` annotations.

So, I tend to reopen this issue until we make the above `@Inherited`, too. What do you guys think?

**Comment by nipafx** [comment]
@beatngu13 Can you open a new issue for these annotations? As I see it, they indeed all need that behavior, so you can also start on working on that if you want. One PR per extension please. :)
