### ISSUE TITLE
Sign artifacts conditionally

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#482]
As pointed out by @fknittel in [this comment](https://github.com/junit-pioneer/junit-pioneer/issues/480#issuecomment-839670979), JUnit Pioneer currently can't be used via JitPack. This is because `publishToMavenLocal` fails as it tries to sign the artifacts ([JitPack log](https://jitpack.io/com/github/junit-pioneer/junit-pioneer/v1.4.1/build.log) on v1.4.1):

```text
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signMavenPublication'.
> Cannot perform signing task ':signMavenPublication' because it has no configured signatory
```

According to the [Signing Plugin docs](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:conditional_signing), signin artifacts conditionally is a common usage pattern. We should do this too, not just to enable JitPack usage, but also to e.g. allow users to conveniently publish to their local Maven repo.

**Comment by nipafx** [comment]
Sounds reasonable.

**Comment by nipafx** [comment]
While reviewing #483, we came across the fact that because `project.version` is "unspecified" (that's the actual value!) except when `-Pversion` is set for a release build, `gradle publishMavenPublicationToMavenLocal` publishes an artifact with that version, which is at least unexpected, maybe it even breaks some tools. I'm not sure whether fixing this issue will be enough to use Pioneer with JitPack. If not, we can work on that in a new issue.
