### ISSUE TITLE
Evaluate using API Guardian

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#499]
JUnit 5 uses [API Guardian](https://github.com/apiguardian-team/apiguardian) to mark their API as stable or experimental (and for other purposes too).

Should we use this?

It might be that this is a stupid question because by the nature of the project all our extensions should be considered experimental.

**Comment by Bukama** [comment]
> It might be that this is a stupid question because by the nature of the project all our extensions should be considered experimental.

I see this and the more need of (imo unnecessary) micro managing as points to not use it.

**Comment by beatngu13** [comment]
>It might be that this is a stupid question because by the nature of the project all our extensions should be considered experimental.

Hmmm, I always thought we are a "serious" project and, therefore, provide stable APIs unless stated otherwise. 😬

From the [API Guardian Javadoc](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.Status.html#EXPERIMENTAL):

>`EXPERIMENTAL`: Intended for new, experimental features where the publisher of the API is looking for feedback.
>
>Use with caution. Might be promoted to `MAINTAINED` or `STABLE` in the future, but might also be removed without prior notice.

Personally, I also understand experimental APIs as potentially breaking between minor releases.

Anyway, I find the use of API Guardian quite interesting to better communicate the status of our various extensions.

**Comment by nipafx** [comment]
Feels like too much micromanagement for a project of our size. And as @Michael1993 said, it's all experimental anyway. 😂
