### ISSUE TITLE
Decide on and maybe include static analysis tool

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#50]
Should we use a static analysis tool? Why? If so, which one?

**Comment by smoyer64** [comment]
As a coder, the FindBugs/JSR-305/SpotBugs annotations provide a way to "finish" specifying the contract specified by each method in a class (and sometimes across methods in a class).  In my opinion, adding the annotations is a pretty trivial exercise and does not add a huge tree of dependencies to the project.  I would argue that we run FindBugs (and find-sec-bugs) regardless of whether we add the annotations (I believe CheckStyle is fully replaced by Spotless?) but adding the annotations allows for better static analysis.

See https://github.com/junit-team/junit5/issues/358 for my proposal to the JUnit 5 team including a real use-case.  See https://github.com/junit-team/junit5/issues/741 for a Kotlin use-case which includes a link that shows that the Kotlin compiler will accept FindBugs or JSR-305 annotations (among others).

**Comment by jbduncan** [comment]
@smoyer64 I believe the JUnit 5 team mainly uses Spotless, but use Checkstyle for one or two small "rules" that Spotless itself does not cover. We might want to go down the same route.

**Comment by jbduncan** [comment]
Regarding static analysis, I argue that we should at least use [error-prone](http://errorprone.info/), since it catches a bunch of easy-to-mess-up things at compile-time, and in my experience is less likely to report false positives than FindBugs.

**Comment by smoyer64** [comment]
@jbduncan I almost included error-prone as a candidate for a static code analysis tool.  I always use the find-sec-bugs plugin FindBugs - does error-prone have an equivalent?

**Comment by jbduncan** [comment]
@smoyer64 I don't think so. I believe one can write custom rules for error-prone to check against, but I've absolutely no experience with this.

I can see that security is a valid concern, so I wouldn't be against us using the find-sec-bugs plugin for FindBugs/SpotBugs as well.

**Comment by jbduncan** [comment]
P.S. Thank you for indirectly introducing me to SpotBugs. I wasn't aware that the FindBugs project had been slowly experiencing less activity and that people were starting to fork it. Perhaps this means that FindBugs has an interesting future as a static analysis tool. :)

**Comment by jbduncan** [comment]
@nicolaiparlog @smoyer64 If the nullability of things like `Optional`, as discussed in https://github.com/junit-pioneer/junit-pioneer/issues/51, is a concern, then we should consider adopting the Checker Framework, which as you may or may not know enhances Java's type system with `@Nullable` et al. to prevent `NullPointerException`s at compile time. I've personally never used it, but I understand that Google are using it internally in some capacity, so it may be a good tool to experiment with.

**Comment by jbduncan** [comment]
In summary, I suggest that we use a combination of the following static analysis and formal verification tools:
- error-prone (for catching miscellaneous errors at compile time)
- SpotBugs (for find-sec-bugs and other errors)
- Checker Framework (for null type checks)

I think that using FindBugs/SpotBugs for null analysis is not a very good idea, because according to the [Checker Framework](https://checkerframework.org/manual/) documentation, sections 3.7.1 and 3.7.2, FindBugs misses some real errors with its null analysis, and apparently it interprets `@Nullable` in a non-standard way that's incompatible with most other tools.

**Comment by smoyer64** [comment]
@jbduncan - There's going to be some overlap but we should end up with thorough checking that way.  If we pass, clearly the code is "bug-free" (wink wink).

**Comment by nicolaiparlog** [comment]
Reviving an age old thread... I'm not convinced we need a static analysis tool. If we still want to use one, I'd advise against the stagnant FindBugs and I'm not yet convinced SpotBugs will fare much better. All that being said, it's not a strong opinion, so if anybody feels like adding it to the build, I'll not stand in the way.

**Comment by smoyer64** [comment]
I'm a fan so asking me is always going to go towards including these checks.  @jbduncan has also convinced me that I need both SpotBugs and ErrorProne!

**Comment by aepfli** [comment]
I add my few cents here.

I am actually a fan of sonarqube/cloud, the tool integration is really good, the insights and overview about different issue types is also great, and it supports a lot of additional analyzers too. eg. SpotBugs/findbugs, CheckStyle etc.

I think there is by now also a really good github integration to decorate pull requests more specifically. 

I also have to say that i am a little sonar fanboy, and we use it in our company too decorate pull requests and to keep changes within a quality gate. As it unifies a lot of tools, i really enjoy it a lot, and the integration with a gradle build is really easy

**Comment by aepfli** [comment]
What does sonarqube offer:
- quality gates
![image](https://user-images.githubusercontent.com/9987394/75819083-43ad5080-5d9a-11ea-8098-420ede882980.png)
- different quality profiles
![image](https://user-images.githubusercontent.com/9987394/75819141-60498880-5d9a-11ea-9787-be4ab70a98fb.png)
- branch based analyses with short living branches see example
![image](https://user-images.githubusercontent.com/9987394/75819327-c504e300-5d9a-11ea-84a1-0dc1a60c9097.png)

What will we see for the project:
- Bugs
- CodeSmells
- Vulnerability issues
- Coverage
- Heatmaps
- Technical Debt

What can we do in future:
- Sonarqube can be extended with generic reports like for SpotBugs, Pitest etc (theoretically, no experience in that)
- depending on the plugin support, there might be interesting additional plugins

What do we need to implement it fully:
1. we need a sonarcloud project for the junit-pioneer team
2. we need to generate a token, which we can use in travisCI
3. this token should be stored on the TravisCI
4. we can add sonarqube as a build step to the project for the branches and you can see the example in https://blog.jdriven.com/2019/08/sonarcloud-github-pull-request-analysis-from-jenkins/


We also could think of removing TravisCI and migrate to github actions.

**Comment by nicolaiparlog** [comment]
Thank you for putting this together, this looks really promising. Besides my TODOs (tokens, etc.) I'm most interested atm to discuss how exactly we want to use this. My thoughts:

* run on master to see where we need to improve
* run on branches to see where they fall short
* let's keep it casual for a while (i.e. not preventing the merge) until we've tuned the analysis to our needs

What are your thoughts?

> We also could think of removing TravisCI and migrate to github actions.

I think this would be a separate issue. ;)

**Comment by aepfli** [comment]
> run on master to see where we need to improve
> run on branches to see where they fall short

that would be a good starting point, we can tweek rules afterwards (like codesmells and assertions, there are some pitfall due to our testclasses within tests ;))

> let's keep it casual for a while (i.e. not preventing the merge) until we've tuned the analysis to our needs

:+1:

to generate some easy and dettached progress i thought of setting up the fork fully with travisCI etc. so i can show off and tweak all the functionality to a really usable status without downsides. We also will have a playground to experiment with build changes and sonarcloud integration and can than if we think this works great merge it. In that case we can also create exisitng pull requests within the fork to test all the functionality.

What is your take on this approach?

**Comment by aepfli** [comment]
additionally i will provide a guide to configure SonarLint - so people can have sonar issues already visible within their IDE

**Comment by aepfli** [comment]
Update from the front, in my fork is set up everything accordingly. And it is working, i even added codecov because i thought there is an issue with coverage, which is not ;D YAY.

I will prepare a pull request next, i did a lot of strange commit, to verify everything is working with travis. need to clean that up. Furthermore, i also need to investigate some more granular build setup. It is more like an improvement, but we are running sonar analysis and testcoverage now for each jdk and we could definitly reduce this, to fewer interactions. But as said this is more of an improvement nature for me currently. so no focus. Maybe i will first investigate github actions.

**Comment by Bukama** [comment]
Totally missed this issue...
I see much value in the usage of SCA tools, especially `Spotbugs` and `PMD` provide useful things. I detect myself quite regular when reading the reports `Oh yeah I missed that possible bug`.

Sonarqube seems like a good place as history can be views. 

Maybe we should implement it (thanks @aepfli for setting up #181) and start to gather data. If we have a feeling about the reported SCA-issues we should decide about a quality gate. But I wouldn't start with a build breaking one without any experience on the rule set. So I also vote for this.

**Comment by nicolaiparlog** [comment]
Related to #192.

**Comment by Bukama** [comment]
@aepfli In my opinion its quite strange that sonarqube doesn't throw violations on as the underlying base (`master` branch) has issues. Does it only checks new/changed code?

**Comment by aepfli** [comment]
yes, sonarqube-scanner with pr analysis only validates your current changed code, so you do not add new issues. This is also a big strength of the sonarqbe imho. Because rules can change, there can be new ones, there can be ones with updated severity, and this can happen during your development. So instead of blocking you with already existing issues, it just forces you to get your changes passed the quality gate.

Additionally there is something which SonarSource (the company behind sonarqube and sonarcloud) called the Water-Leak-Principle. Lets say your sink is leaking, and you have a big pool of water in the kitchen. The first thing you do is stopping the water, and not cleaning up the pool. This analogy can be simply applied to sonarqube/sonarcloud. Instead of fixing or forcing you to fix old issues, it prevents you from creating new ones.

In this project, this is not a big deal imho. But when you have big legacy projects, you will not be able to fix all the issues :) - either by resources or also by risk, could you touch oppose a risk of bugs.

**Comment by Bukama** [comment]
Thanks for explanation 👍

**Comment by Bukama** [comment]
@aepfli @nicolaiparlog  Shall we close this bishue? We have introduced sonar and even that #192 is not done yet, I think it's not so important to keep this here open.

**Comment by aepfli** [comment]
Agree, if we want other tools, we could evaluate them separately

**Comment by Bukama** [comment]
As we have introduced sonar and we both see shipkit unrelated to SCA I'll close this ticket.
