### ISSUE TITLE
Setting environment fails on Java 17-ea

### ISSUE THREAD

**Issue by cescoffier** [junit-pioneer/junit-pioneer#509]
I have a few tests using the `@SetEnvironmentVariable` annotation. Unfortunately, at the moment, they fail on Java 17 (EA) with:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.HashMap java.lang.ProcessEnvironment.theEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @527b7298
```

**Comment by Michael1993** [comment]
There is really no nicer way to say this: you should have read the documentation. Here is the relevant section:

## Warnings for Reflective Access

As explained above, this extension uses reflective access to change the otherwise immutable environment variables.
On Java 9 to 16, this leads to a warning like the following:

```
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.junitpioneer.jupiter.EnvironmentVariableUtils [...] to field [...]
[ERROR] WARNING: Please consider reporting this to the maintainers of org.junitpioneer.jupiter.EnvironmentVariableUtils
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
```

On Java 17 and later, you get this error instead:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field [...] accessible:
module java.base does not "opens java.lang" to unnamed module [...]
```

The best way to prevent these warnings/errors, is to change the code under test, so this extension is no longer needed.
The next best thing is to allow access to that specific package with `--add-opens=java.base/java.util=ALL-UNNAMED` (if you place JUnit Pioneer on the class path) or `--add-opens=java.base/java.util=org.junitpioneer` (if you place it on the module path).

These command line options need to be added to the JVM that executes the tests:

* [https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html](Gradle)
* [http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine](Maven basics) and [https://nipafx.dev/maven-on-java-9/](advanced)

**Comment by Michael1993** [comment]
We can't (and shouldn't try to) work around this issue. You can read more about it on the Oracle blog: [A peek into Java 17: Continuing the drive to encapsulate the Java runtime internals](https://blogs.oracle.com/javamagazine/java-runtime-encapsulation-internals).

The next best thing I can suggest is looking into testcontainers. Sorry!

**Comment by cescoffier** [comment]
Oh sorry, I missed that in the doc.

**Comment by ashleyfrieze** [comment]
This issue could be solved - see https://github.com/webcompere/system-stubs/blob/main/system-stubs-core/src/main/java/uk/org/webcompere/systemstubs/environment/EnvironmentVariableMocker.java 

The solution involves depending on `mockito-inline`, but is easily adopter. You could reasonably copy the above code, or could add the above as a dependency for JUP.

I'm the author of the above class, so feel free to use it as you wish.

**Comment by beatngu13** [comment]
@ashleyfrieze thx for informing us – we will have a look! 🙏

**Comment by ashleyfrieze** [comment]
> @ashleyfrieze the static mocking works, but you also need to handle calls to `getenv()` and `environment()` not just `getenv(String)`. `environment()` also has to return something that will cast to `ProcessEnvironment`, which probably means it has to be another mock.

Thanks @OrangeDog  - please see the issue here - https://github.com/webcompere/system-stubs/issues/40 - I have a PR which "fixes" that. Please feel free to review and comment before I merge and release later.
