### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#589]
So far we do not have a lot of Issues created, but there is still an inconsistency about the creation process.

Some are labelled, some are not, and some are totally differently labelled. 

To reduce the efforts for us maintainers, we should provide at least following types of templates to reduce the initial effort:

- Feature request
- Bug
- Question
- Other

Based on this types we can easier label the topics, and also provide better templates with dedicated questions. see https://github.com/renovatebot/renovate/tree/main/.github/ISSUE_TEMPLATE

**Comment by RishiKumarRay** [comment]
@aepfli do you want the templates in the same format or you wish to add any other fields?

**Comment by Bukama** [comment]
> @aepfli do you want the templates in the same format or you wish to add any other fields?

I think it were just some thoughts of most probably helpful things, but not a stoned list

**Comment by aepfli** [comment]
maybe it is also worth to maybe extract this into a .github repository like described here https://www.freecodecamp.org/news/how-to-use-the-dot-github-repository/

**Comment by Bukama** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

That's the official Github docu to create issue templates.

**Comment by Bukama** [comment]
A first draft for a bug report to get some response if the base tune is okay. Would then make a draft for a feature request too.

My goal is to request all useful information, without overloading the template. I'm even not sure if the JUnit Jupiter and Java version are that relevant.

![image](https://user-images.githubusercontent.com/4354359/188266203-362100ec-07de-48d9-95ab-500dda759fdb.png)

So what do you think? @Michael1993 @aepfli @nipafx @beatngu13 and all others?

Note: I've created the template in one of my own repositories, because in Pioneers settings I don't have the rights too. Of course in the end i need to open a PR with the templates inside `.github´ folder.

**Comment by Michael1993** [comment]
LGTM

**Comment by Bukama** [comment]
Example for feature request. I'm not totally happy with it, but that's more that I'm not very creative what people might suggest and I didn't want to make the template too complex.

![featurerequest](https://user-images.githubusercontent.com/4354359/189474712-55e7b842-eba0-4ed3-8b1e-3dbdb16d5fde.png)

**Comment by nipafx** [comment]
These look good to me. I think you can open a PR with those - if we find room to improve, we can always do that down the road. IIRC, there's always a button to create an empty issue, so I don't think we need templates for Question or Other.

Please also look into CONTRIBUTING.md to see whether this change needs to be mentioned there. (Maybe not, in which case, we don't need to add anything, either.)
