### ISSUE TITLE
Upgrade Gradle and pipeline when Java 18 is supported

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#613]
As of writing Gradle does not support Java 18, according to: https://docs.gradle.org/current/userguide/compatibility.html

This means we can't upgrade our build pipeline to use it, which is what we want to

> beatngu13: I mean once Gradle is ready for Java 18. What versions are we aiming for as part of our full build?
> nipafx: 11, 17, 18

**Comment by aepfli** [comment]
I am pretty sure we are not blocked here. There is a difference within our experimental build, regarding which version of java Gradle is using, and which one we are using for the actual build. Yes Gradle is not java 18 compatible, but it does not need to be. We only need to execute the build itself with 18 and Gradle with eg. 17

**Comment by Bukama** [comment]
Java 18 is now supported by Gradle 7.5 according to the matrix

**Comment by beatngu13** [comment]
Regarding:

>nipafx: 11, 17, 18

We currently "only" include 11 and 17:

https://github.com/junit-pioneer/junit-pioneer/blob/main/.github/workflows/build.yml#L120

Adding 18, not just replacing 17, will increase build time as we include an additional element to combine. Also, JUnit Jupiter 5.9.0-RC1 has been released:

https://junit.org/junit5/docs/snapshot/release-notes/#release-notes-5.9.0-RC1

Since we probably also want to include this version, we get another element to combine.

**Comment by nipafx** [comment]
As you propose in #651, we should build against 18/19, though, so let's do that.
