### ISSUE TITLE
Auto import of @Enum annotation not possible in eclipse

### ISSUE THREAD

**Issue by heribender** [junit-pioneer/junit-pioneer#753]
Noticed in eclipse 2023-03, with pioneer 2.0.1

The eclipse setting java/editor/ContentAssist/Favorites can define embedded static members and methods that the auto import generator can resolve.

![image](https://github.com/junit-pioneer/junit-pioneer/assets/7716755/3881c33d-3a0e-4129-94ff-8866d7604f0c)

Defining org.junitpioneer.jupiter.cartesian.CartesianTest.* allows to auto import the `@Values` annotation, but not the `@Enum` annotation.

I assume this is because 'Enum' is a reserved word in java.

Unfortunatly the eclipse setting java/editor/ContentAssist/Favorites does not accept org.junitpioneer.jupiter.cartesian.CartesianTest.Enum as standalone type. On save it suffixes it by a '.*' as shown in above screenshot.

Probably a renaming of this `@Enum` annotation could solve the problem? E.g. `@EnumSource`?

**Comment by Bukama** [comment]
Hey, thank your for your submission.
We will have a discussion about it, if we consider this a problem of Pioneer or of Eclipse (for what we are not responsible)

**Comment by beatngu13** [comment]
@heribender it has been a while since I have used Eclipse, so please bear with me. 😉

The [latest Eclipse documentation](https://help.eclipse.org/2023-03/index.jsp) (I have no idea how to link to the actual page, but it is under Java development user guide > Reference > Preferences > Java > Editor > Content Assist > Java Content Assist Favorites Preferences) says:

>You can define a list of static members and types containing static members on this page [i.e. favorites]. Content assist will propose those members even if the import is missing.

[`org.junitpioneer.jupiter.cartesian.CartesianTest.Enum`](https://github.com/junit-pioneer/junit-pioneer/blob/v2.0.1/src/main/java/org/junitpioneer/jupiter/cartesian/CartesianTest.java#L180) is a nested _annotation_ interface. Nested interfaces are implicity `static` (see [JLS 9.1.1.3](https://docs.oracle.com/javase/specs/jls/se20/html/jls-9.html#jls-9.1.1.3)). Not sure if this applies to nested annotation interfaces as well, but even if I don't add `CartesianTest.Enum` to my favorites, content assist seems to work fine:

<img width="1920" alt="Bildschirmfoto 2023-09-08 um 21 36 11" src="https://github.com/junit-pioneer/junit-pioneer/assets/11643714/efc21e38-a16c-44b3-a238-6e1350e3162a">

<img width="703" alt="Bildschirmfoto 2023-09-08 um 21 37 10" src="https://github.com/junit-pioneer/junit-pioneer/assets/11643714/cf57ec5e-c06b-4f06-ae0b-779e971a3cb5">

Tested with Eclipse IDE for Java developers:

* Version: 2023-06 (4.28.0)
* Build ID: 20230608-1333

---

>I assume this is because 'Enum' is a reserved word in java.

I don't think this is the case. lower case `enum` is a keyword (see [JLS 3.9](https://docs.oracle.com/javase/specs/jls/se20/html/jls-3.html#jls-3.9)), upper case `Enum` isn't.

>Probably a renaming of this `@Enum` annotation could solve the problem? E.g. `@EnumSource`?

This would be a breaking change. Also, I don't see a problem at the moment.

What behaviour do you expect from Eclipse that isn't working with Pioneer / `CartesianTest.Enum`?

**Comment by heribender** [comment]
@beatngu13: Thanks for your response.

As you see in my screenshot, the eclipse version 2023-03 shows basically the same text in the Favorites property setting page as you show. And as you see also there, that I have defined the org.junitpioneer.jupiter.cartesian.CartesianTest as a class that contains static members.

And yes, the embedded static annotation `@Values` is proposed automatically by the eclipse tooling, but not the `@Enum` annotation, which is in the same file and on the same level as the former one.

Obviously, your newer eclipse version 2023-06 has fixed this problem. I will give it a try.

**Comment by beatngu13** [comment]
@heribender as it appears to work with the newest Eclipse version, I'm going to close this issue.

If you still face problems, feel free to re-open. ✌️
