### ISSUE TITLE
Consier add API for Stress Testing

### ISSUE THREAD

**Issue by manueljordan** [junit-pioneer/junit-pioneer#81]
I had the following idea or mostly request,  and for suggestion of Sam Brannen I arrived here:

And according with the [About the Project](http://junit-pioneer.org/junit-pioneer/) page, it contains:

> if you have an idea for an extension you could make good use of, open an issue

Just curious, I want to know if has sense for `JUnit 5` ask for or suggest a new feature: 

API to simulate and have automatization for _stress testing_ for some common scenarios: 

* Network 
* Database. It about simulating 'fake' user connections without matter the db provider, and of course many of these interacting with the DB (reading and writing). 

Has sense for you?  You are the experts

**Comment by nicolaiparlog** [comment]
> You are the experts

We are the experts on JUnit 5 and Pioneer, but you are the expert on your use case. :wink: Can you describe in a little more detail what exactly Pioneer could do here? Maybe you can give an example of what such a test would ideally look like with regards to setup, execution, and assertion.

I have no experience with stress tests, but I could imagine that a user might want to specify an action, the "amount" of parallelism and expected results, e.g. for latency. The test would than have to take that action, run it as prescribed, track the results and compare them with the expected results. Assuming the statistics can be properly represented by a single class, the last step could be done with the assertions of the user's choice.

**Comment by marcphilipp** [comment]
Have you tried [Gatling](https://gatling.io/)?

**Comment by manueljordan** [comment]
Thanks for the valuable link. No never, I will do a research. Thank you.

**Comment by nicolaiparlog** [comment]
@manueljordan See, some expert showed up to help you. :wink: If your research shows that you don't need JUnit Pioneer to help you out, please remember to close this issue.

**Comment by manueljordan** [comment]
Thank you. 

Even when exists the tool and is not free and is only for web development. Consider again the case to test the uses cases in the server side directly calling either a `@Service` or `@Repository`. 

Just curious if is possible add the feature requested to this software. 

I will do a research this weekend about `Gatling`

**Comment by Bukama** [comment]
When doing stress or performance testing you have an large amount of different requirements for this parallel execution and the endpoints you want to test. As there are a large amount of tools who focus on this part of testing, like `Gatling`, `SOAPUI`, `JMeter`, `LoadRunner` and much much more I don't think Pioneer can provide an extension which could compete with those specialized tools. Even because the focus of Pioneer as an Unittest extension has a different focus on testing and test execution - simple said: Testing the correct functional execution of the system under test during development / build, while performance testing tools focus on (simple said) testing a deployt application and its environment.

This why I would like to close this issue.

--
Requesting @aepfli , @Michael1993 , @beatngu13

**Comment by nicolaiparlog** [comment]
I think such features can have a place in JUnit Pioneer and if anybody wants to open a PR, that would be ok. I agree that this has a large scope, so it could even become its own project under the Pioneer umbrella.

That said, I don't see us implementing and maintaining this at the moment and will close the issue.

**Comment by Bukama** [comment]
> That said, I don't see us implementing and maintaining this at the moment and will close the issue.

*Pushing the button for Nicolai*
