### ISSUE TITLE
junit-pioneer not release since last year | any release plan?

### ISSUE THREAD

**Issue by hsebouai** [junit-pioneer/junit-pioneer#824]
Hi 👋,

Thank you for this library, it helped us a lot to have better tests.

We noticed that the library has not been updated on maven central since last year (Nov 16, 2023) despite recent activities (commit, PR merge, etc..) on the repository.

- Is it intentional that the library has not been released since last year? 
- Do you publish updates/release on another maven repository?

Can you help us with that and thank you in advance.

**Comment by Michael1993** [comment]
Hi @hsebouai !

Thank you for your interest in the project.
We are all rather busy doing other things and I'll admit that's why Pioneer is stagnating.
When we released 2.0, we still had a couple things we wanted to work on urgently and we released a lot more frequently. Since then life got busy for all of us and, since we did most of the things we wanted to have in 2.0 in follow-up releases, we wound down a little bit.

That is not to say we are not still enthusiastic about Pioneer! We still try to follow up on all issues and ideas, just a bit more slowly. If you would like to contribute, please share your ideas and we can have a discussion. We are looking for new contributors. 😉

**Comment by beatngu13** [comment]
And we have a milestone for 2.3.0:

https://github.com/junit-pioneer/junit-pioneer/milestone/8

**Comment by beatngu13** [comment]
Thanks for kicking our butt, 2.3.0 just went out. 😉

https://github.com/junit-pioneer/junit-pioneer/releases/tag/v2.3.0
