### ISSUE TITLE
Build script clean-up

### ISSUE THREAD

**Issue by sormuras** [junit-pioneer/junit-pioneer#96]
Collection of various issues that need to be addressed:

1. Merge `./.infra/gradle/` into `./gradle/` -- why is the gradle-wrapper not in the default place anyway? Makes importing the project via the default wizards in IDEA impossible.
2. Use single source `pom.xml`: Shipkit generates one from project properties vs. `build.gradle` contains an obsolete(?) one.
3. Shipkit generates `./docs/release-notes.md` ... link it into the main documentation?
4. Add link to https://javadoc.io/doc/org.junit-pioneer/junit-pioneer for browsable API docs, different versions included.

**Comment by nicolaiparlog** [comment]
Re:

1. GitHub, Checkstyle, Gradle, Travis, Appveyor, none of them are essential to the project and still their configurations eat up tons of attention and vertical space. I banished what I could into `.infra` to reduce the clutter. We should look into whether it's possible to move `shipkit.gradle` into `.infra/shipkit` or `.infra/gradle`.
2. If your assumption is correct that the one in `build.gradle` is no longer needed, we should indeed remove it. But we need to make sure that the information (project site, developers, etc) can be represented in `shipkit.gradle`.
3. I've been thinking about that one, see #97.
4. If you're talking about a link from junit-pioneer.org to javadoc.io, see #92. Otherwise, can you explain where you want to add that link?

**Comment by sormuras** [comment]
- ad 1: I see. Guess it is not possible atm, right @mockitoguy? Maybe we need to open a question issue at https://github.com/mockito/shipkit/issues 
- ad 2: Good suggestion. As as I can tell, Shipkit collects information for the `pom.xml` from different source. Didn't find a way yet to customize the resulting `pom.xml` directly.
- ad 4: 92 will tackle it -- missed that ticket

**Comment by nicolaiparlog** [comment]
Current state of affairs:

1. this got sidetracked:
	a. in #190, we just decided to move the Gradle wrapper :heavy_check_mark: 
	b. for ShipKit, see #193 :heavy_check_mark: 
2. folded into #193 :heavy_check_mark: 
3. see #97 :heavy_check_mark:
4. see #92 :heavy_check_mark:
